trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: Checkout@1
  displayName: 'Checkout Repository'

- task: UseDotNet@2
  displayName: 'Set up .NET SDK'
  inputs:
    packageType: 'sdk'
    version: '6.x'
    installationPath: $(Agent.ToolsDirectory)/dotnet

- script: dir
  displayName: 'List Directory Contents'

- script: |
    dotnet build src/ZeroTrustAssessment.sln --configuration $(buildConfiguration)
  displayName: 'Build Solution'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Build Artifacts'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
